[Dock]
pinnedApps="[{\"id\":\"ghostty\",\"label\":\"Ghostty\",\"icon\":\"com.mitchellh.ghostty\",\"execName\":\"\",\"steamId\":\"\"},{\"id\":\"zeditor\",\"label\":\"Zed\",\"icon\":\"zed\",\"execName\":\"\",\"steamId\":\"\"},{\"id\":\"spotify\",\"label\":\"Spotify\",\"icon\":\"spotify\",\"execName\":\"\",\"steamId\":\"\"},{\"id\":\"org.gnome.Nautilus\",\"label\":\"Files\",\"icon\":\"system-file-manager\",\"execName\":\"nautilus\",\"steamId\":\"\"}]"

[Launcher]
appUsage="{\"zen\":3,\"zeditor\":2,\"steam_app_431730\":3,\"org.gnome.Nautilus\":2,\"bitwig-studio\":1,\"spotify\":8,\"ghostty\":3,\"firefox\":18,\"bitwarden\":1,\"dev.zed.Zed\":15,\"code\":2,\"discord\":2}"
hiddenApps=
isGridView=false

[System]
isBatterySaverActive=false
lastBrightness=100
nightLightOn=false
preSaverBrightness=100
preSaverProfile=1
wasManuallyOverridden=false

[Theme]
isDark=true
